### ISSUE TITLE
Markdown image links don't work

### ISSUE THREAD

**Issue by BobBorges** [MicroPad/MicroPad-Core#308]
**Describe the bug**
Image links don't seem to work in Markdown elements.

**To Reproduce**
- Create Notebook and note.
- insert text element with markdown.
- add img links e.g. 
    - `![img](path/to/local.png)`

**Expected behavior**
I would expect images to get embedded in the text card and appear in the print/pdf when generated.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser firefox 87.0
 - Version 3.27.0

**Comment by NickGeek** [comment]
Hi,
I've looked into this and I don't think there's anything that could be done because of how modern web browsers do security. Both Firefox and Chrome block requests to `file://` resources from a `http(s)://` resource (like MicroPad).

If anyone knows of a workaround I'd be keen to hear it, but for now it seems like browsers have decided that it's not possible to do so for privacy reasons.
