### ISSUE TITLE
Feature request: multiple pen colours

### ISSUE THREAD

**Issue by reidwicks** [MicroPad/MicroPad-Core#65]

**Comment by rohithreddy** [comment]
Hey, I am interested in working on this, can you help me and give me any pointers related to code ? or how we can accomplish this

**Comment by NickGeek** [comment]
@rohithreddy That'd be awesome, thanks!
All the drawing logic is in: https://www.github.com/MicroPad/MicroPad-Core/tree/master/app%2Fsrc%2Fapp%2Fcomponents%2Fnote-viewer%2Felements%2Fdrawing%2FDrawingElementComponent.tsx

Right now I use booleans to decide what to draw, you could change that to an enum of colours and then add a dropdown in the UI to select the colour.

Alternatively you could have a colour picker in the UI and then store the current selected colour as a string, enabling the user to use any colour.

**Comment by Jonas-July** [comment]
Hi, did something come out of that? I couldn't find anything.
Using the current next-dev, I created a prototype where choosing different colours is already possible:
https://github.com/Jonas-July/MicroPad-Core/tree/new-colours

Unfortunately, I'm not familiar enough with Materialize to use Radiobuttons for colour selection, so that behaviour is emulated using Checkboxes. I'd be glad if one would provide me with documentation or code samples to help in that regard.

Next I'd like to replace the text with images of that colour. The logic for rainbow colouring also seems a bit complex for what it does, but that's a different issue.
Feedback with regards to my changes so far would be appreciated. I'd like to work on this until it is merged and learn some more about the frameworks used.

Regards, Jonas

**Comment by NickGeek** [comment]
@Jonas-July Thanks for looking into this! If you open a Draft PR it'll be easier to track those changes. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color is what I imagine would be the best approach for the colour selector.

Also, yeah that rainbow logic could definitely be simplified.
